# Generated by Django 5.0.6 on 2024-05-13 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, verbose_name='제품명')),
                ('image', models.ImageField(blank=True, default='static/images/defaultimg.jpg', null=True, upload_to='static/images', verbose_name='이미지업로드')),
                ('body', models.TextField(null=True, verbose_name='내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('plink', models.CharField(max_length=100, verbose_name='링크주소')),
                ('status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10, verbose_name='노출여부')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='글쓴이')),
            ],
            options={
                'verbose_name': '제품등록',
                'verbose_name_plural': '제품등록',
                'ordering': ['-created'],
            },
        ),
    ]
