# Generated by Django 5.0.6 on 2024-05-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='이름(상호)')),
                ('number', models.CharField(max_length=50, null=True, verbose_name='전화번호')),
                ('body', models.TextField(null=True, verbose_name='내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('신규', '신규'), ('완료', '완료'), ('진행중', '진행중'), ('보류', '보류')], default='신규', max_length=10, verbose_name='status')),
                ('terms_confirmed', models.BooleanField(max_length=10, null=True, verbose_name='개인정보 수집 동의')),
            ],
            options={
                'verbose_name': '랜딩페이지DB',
                'verbose_name_plural': '랜딩페이지DB',
                'ordering': ['-created'],
            },
        ),
    ]
