# Generated by Django 5.0.6 on 2024-05-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': '문의하기DB', 'verbose_name_plural': '문의하기DB'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='imglink',
            field=models.CharField(default='https://sotoairpurifier-oss.oss-cn-beijing.aliyuncs.com/attached/image/20210607/20210607135313_9390.jpg', max_length=100, verbose_name='이미지링크'),
        ),
        migrations.AlterField(
            model_name='product',
            name='plink',
            field=models.CharField(max_length=100, verbose_name='링크주소[제품코드]'),
        ),
    ]
