# Generated by Django 5.0.6 on 2024-05-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_post_options_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imglink',
            field=models.CharField(default='https://sotoairpurifier-oss.oss-cn-beijing.aliyuncs.com/attached/image/20210607/20210607135313_9390.jpg', max_length=200, verbose_name='이미지링크'),
        ),
    ]
