# Generated by Django 5.0.6 on 2024-05-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_product_imglink_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='staticfiles/images/defaultimg.jpg', null=True, upload_to='staticfiles/images/', verbose_name='이미지업로드'),
        ),
    ]
