# Generated by Django 5.0.6 on 2024-05-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/images/defaultimg.jpg', null=True, upload_to='static/images', verbose_name='이미지업로드'),
        ),
    ]
