# Generated by Django 5.0.6 on 2024-06-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_product_image_alter_product_plink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='terms_confirmed',
        ),
    ]
