# Generated by Django 5.0.6 on 2025-06-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_collectingdb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectingdb',
            options={'ordering': ['-created'], 'verbose_name': '검사신청DB', 'verbose_name_plural': '검사신청DB'},
        ),
        migrations.AddField(
            model_name='collectingdb',
            name='promoperson',
            field=models.CharField(max_length=50, null=True, verbose_name='추천인'),
        ),
    ]
