# Generated by Django 5.0.6 on 2025-06-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_collectingdb_address001_collectingdb_address002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectingdb',
            name='address001',
            field=models.CharField(choices=[('서울특별시', '서울특별시'), ('부산광역시', '부산광역시'), ('인천광역시', '인천광역시'), ('대구광역시', '대구광역시'), ('광주광역시', '광주광역시'), ('대전광역시', '대전광역시'), ('세종특별자치시', '세종특별자치시'), ('경기도', '경기도'), ('강원도', '강원도'), ('충청북도', '충청북도'), ('충청남도', '충청남도'), ('경상북도', '경상북도'), ('경상남도', '경상남도'), ('전라북도', '전라북도'), ('전라남도', '전라남도'), ('제주특별자치도', '제주특별자치도')], max_length=10, null=True, verbose_name='주소1'),
        ),
    ]
