# Generated by Django 5.0.6 on 2025-06-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_collectingdb_address001'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectingdb',
            name='dhname',
            field=models.CharField(max_length=50, null=True, verbose_name='치과명'),
        ),
    ]
