# Generated by Django 5.0.6 on 2025-06-17 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_collectingdb_dhname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectingdb',
            name='address002',
        ),
    ]
