# Generated by Django 5.0.6 on 2025-06-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_collectingdb_address002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectingdb',
            name='body',
        ),
    ]
