# Generated by Django 5.0.6 on 2025-06-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_collectingdb_cate001_alter_collectingdb_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectingdb',
            name='cate001',
            field=models.CharField(choices=[('구매', '구매'), ('렌탈', '렌탈')], max_length=10, null=True, verbose_name='구매/렌탈'),
        ),
    ]
