# Generated by Django 5.0.6 on 2025-06-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_collectingdb_cate001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectingdb',
            name='address001',
            field=models.CharField(choices=[('서울(서울이남)', '서울(서울이남)'), ('서울(서울이북)', '서울(서울이북)'), ('경기북부', '경기북부'), ('경기남부', '경기남부'), ('인천광역시', '인천광역시'), ('강원도', '강원도'), ('충청남도', '충청남도'), ('대전광역시', '대전광역시'), ('충청북도', '충청북도'), ('세종시', '세종시'), ('부산광역시', '부산광역시'), ('울산광역시', '울산광역시'), ('대구광역시', '대구광역시'), ('경상북도', '경상북도'), ('경상남도', '경상남도'), ('전라남도', '전라남도'), ('광주광역시', '광주광역시'), ('전라북도', '전라북도'), ('제주시', '제주시')], max_length=10, null=True, verbose_name='주소'),
        ),
    ]
