# Generated by Django 5.0.6 on 2025-06-17 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_collectingdb_address001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectingdb',
            options={'ordering': ['-created'], 'verbose_name': '딜러DB', 'verbose_name_plural': '딜러DB'},
        ),
    ]
