# Generated by Django 5.0.6 on 2025-06-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_collectingdb_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectingdb',
            name='status2',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10, verbose_name='판매확정여부'),
        ),
    ]
