# Generated by Django 5.0.6 on 2025-06-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_collectingdb_status2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectingdb',
            name='status2',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10, verbose_name='구매확정여부'),
        ),
    ]
