# Generated by Django 5.0.6 on 2025-06-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_collectingdb_status2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectingdb',
            name='number',
            field=models.CharField(max_length=50, null=True, verbose_name='휴대폰번호'),
        ),
    ]
