# Generated by Django 5.0.6 on 2025-06-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_collectingdb_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collectingdb002',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate001', models.CharField(choices=[('구매', '구매'), ('렌탈', '렌탈')], max_length=10, null=True, verbose_name='구매/렌탈')),
                ('dhname', models.CharField(max_length=50, null=True, verbose_name='치과명')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='성함')),
                ('number', models.CharField(max_length=50, null=True, verbose_name='휴대폰번호')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('신규', '신규'), ('완료', '완료'), ('진행중', '진행중'), ('보류', '보류')], default='신규', max_length=10, verbose_name='status')),
                ('status2', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10, verbose_name='구매확정여부')),
                ('terms_confirmed', models.BooleanField(max_length=10, null=True, verbose_name='개인정보 수집 동의')),
                ('address001', models.CharField(choices=[('서울(서울이남)', '서울(서울이남)'), ('서울(서울이북)', '서울(서울이북)'), ('경기북부', '경기북부'), ('경기남부', '경기남부'), ('인천광역시', '인천광역시'), ('강원도', '강원도'), ('충청남도', '충청남도'), ('대전광역시', '대전광역시'), ('충청북도', '충청북도'), ('세종시', '세종시'), ('부산광역시', '부산광역시'), ('울산광역시', '울산광역시'), ('대구광역시', '대구광역시'), ('경상북도', '경상북도'), ('경상남도', '경상남도'), ('전라남도', '전라남도'), ('광주광역시', '광주광역시'), ('전라북도', '전라북도'), ('제주시', '제주시')], max_length=10, null=True, verbose_name='지역')),
                ('promoperson', models.CharField(max_length=50, null=True, verbose_name='추천인')),
            ],
            options={
                'verbose_name': '상담신청DB',
                'verbose_name_plural': '상담신청DB',
                'ordering': ['-created'],
            },
        ),
    ]
